<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>My first Zend Framework App</title>
    </head>
<body>
    <h1><?php echo $this->name; ?></h1>
    <table border='1'>
        <tr>
            <th>Usuário</th>
            <th>Senha</th>
            <th>Apelido</th>
            <th>Cargo</th>
        <tr>
            <td><?php echo $this->login; ?></td>
            <td><?php echo $this->pass; ?></td>
            <td><?php echo $this->last_name; ?></td>
            <td><?php echo $this->position; ?></td>
        </tr>
    </table>    
</body>
</html>