<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Scoa</title>
    <meta http-equiv="content-type" content="text/html;charset=iso-8859-1" />
    <meta name="description" content="Scoa Sistema de controle Allink" />
    <meta name="author" content="Allink Transportes Internacionais Ltda" />
    <meta name="robots" content="noindex,nofollow" />
    <meta name="robots" content="noarchive" />
    <link href="scoa.css" rel="stylesheet" type="text/css" />
    <?php echo $this->headLink()->appendStylesheet('/Estilos/scoa.css'); ?>
    <?php echo $this->headScript()->appendFile('/Libs/jquery/jquery.js'); ?>  
    <?php echo $this->headScript()->appendFile($this->baseUrl().'/assets/js/clientes/pesquisar.js');?>  
</head>
<body>	
	<div class="principal">
		<p class="titulo">Clientes Encontrados</p>
		<table class="tabela_scoa">
		    <thead>
		        <tr>
		            <th>Cpf / Cnpj</th>
		            <th>Razão</th>
		            <th>Cidade</th>
		            <th>Estado</th>
		            <th>Selecionar</th>
		        </tr>
		    </thead>
		    <tbody>
		    	<?php foreach($this->clientes_encontrados as $cliente): ?>
		        <tr>
		            <td><?php echo $cliente->cnpj; ?></td>
		            <td><?php echo $cliente->razao; ?></td>
		            <td>
		            	<?php 
		            		$cidade = $cliente->findDependentRowset('Application_Model_Cliente_Cidade'); 
		            		echo $cidade[0]->cidade;
		            	?>
		            </td>
		            <td><?php echo $cliente->estado;?></td>
		            <td><?php echo $this->formCheckbox("id_cliente",$cliente->id_cliente,Array('razao' => $cliente->razao));?></td>
		        </tr>
		        <?php endforeach;?>	       
		    </tbody>
		</table>
	</div>
</body>
</html>